[global]
# File watching configuration
fileWatcherType = "auto"
runOnSave = true

# Development settings
developmentMode = false
showWarningOnDirectExecution = false

[server]
# Server configuration
headless = true
port = 8501
maxUploadSize = 200
maxMessageSize = 200

# Security settings
enableCORS = false
enableXsrfProtection = true

# Performance settings
enableStaticServing = true
runOnSave = true
fileWatcherType = "auto"

[browser]
# Browser settings
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
# Custom theme matching your app design
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
# Client settings
caching = true
displayEnabled = true
showErrorDetails = true

[logger]
# Logging configuration
level = "info"
messageFormat = "%(asctime)s %(message)s"

[runner]
# Runner settings
magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true
fastReruns = true

[mapbox]
# Mapbox token (if needed for maps)
# token = "your_mapbox_token"

[deprecation]
# Deprecation warnings
showPyplotGlobalUse = false
showfileUploaderEncoding = false